language:
    java
before_install:
    - sudo apt-get install texlive-latex-base
#- "sudo apt-get update && sudo apt-get install --no-install-recommends texlive-fonts-recommended texlive-latex-extra texlive-fonts-extra texlive-latex-recommended dvipng"
    - git submodule update --init
jdk:
    - openjdk7
script:
    - ant test
    - pdflatex entwuerfe/projektSpezifikation/Projektspezifikation.tex

